repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: check-ast
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: requirements-txt-fixer

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: c60c980e561ed3e73101667fe8365c609d19a438 # v0.15.9
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0397b68f6f88c024f1d2b355a9818779f6336d16 # 0.11.3
    hooks:
      - id: uv-lock
      - id: uv-export